// Generated by scripts/generate-vendor.mjs from the real pnpm resolution
// graph (fixed-point bare-specifier scan). Regenerate after a vendored
// dependency version bump or a new bare specifier enters workspace source.
export const vendorPackages = [
  {
    "name": "zod",
    "version": "4.4.3"
  },
  {
    "name": "webjsx",
    "version": "0.0.73"
  },
  {
    "name": "clsx",
    "version": "2.1.1"
  },
  {
    "name": "anser",
    "version": "2.3.5"
  },
  {
    "name": "diff",
    "version": "9.0.0"
  },
  {
    "name": "katex",
    "version": "0.16.47"
  },
  {
    "name": "shiki",
    "version": "4.3.1"
  },
  {
    "name": "@shikijs/langs",
    "version": "4.3.1"
  },
  {
    "name": "@tanstack/virtual-core",
    "version": "3.17.8"
  },
  {
    "name": "mdast-util-from-markdown",
    "version": "2.0.3"
  },
  {
    "name": "mdast-util-gfm",
    "version": "3.1.0"
  },
  {
    "name": "mdast-util-math",
    "version": "3.0.0"
  },
  {
    "name": "micromark-core-commonmark",
    "version": "2.0.3"
  },
  {
    "name": "micromark-extension-gfm",
    "version": "3.0.0"
  },
  {
    "name": "micromark-extension-math",
    "version": "3.1.0"
  },
  {
    "name": "micromark-factory-space",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-character",
    "version": "2.1.1"
  },
  {
    "name": "micromark-util-classify-character",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-sanitize-uri",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-symbol",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-types",
    "version": "2.0.2"
  },
  {
    "name": "@freddie/freddie-client-web",
    "version": "0.1.1-rc.2"
  },
  {
    "name": "@shikijs/core",
    "version": "4.3.1"
  },
  {
    "name": "@shikijs/engine-javascript",
    "version": "4.3.1"
  },
  {
    "name": "micromark-util-combine-extensions",
    "version": "2.0.1"
  },
  {
    "name": "micromark-extension-gfm-autolink-literal",
    "version": "2.1.0"
  },
  {
    "name": "micromark-extension-gfm-footnote",
    "version": "2.1.0"
  },
  {
    "name": "micromark-extension-gfm-strikethrough",
    "version": "2.1.0"
  },
  {
    "name": "micromark-extension-gfm-table",
    "version": "2.1.1"
  },
  {
    "name": "micromark-extension-gfm-tagfilter",
    "version": "2.0.0"
  },
  {
    "name": "micromark-extension-gfm-task-list-item",
    "version": "2.1.0"
  },
  {
    "name": "micromark-util-encode",
    "version": "2.0.1"
  },
  {
    "name": "@shikijs/types",
    "version": "4.3.1"
  },
  {
    "name": "@shikijs/primitive",
    "version": "4.3.1"
  },
  {
    "name": "@shikijs/vscode-textmate",
    "version": "10.0.2"
  },
  {
    "name": "hast-util-to-html",
    "version": "9.0.5"
  },
  {
    "name": "mdast-util-to-string",
    "version": "4.0.0"
  },
  {
    "name": "micromark",
    "version": "4.0.2"
  },
  {
    "name": "micromark-util-decode-numeric-character-reference",
    "version": "2.0.2"
  },
  {
    "name": "micromark-util-decode-string",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-normalize-identifier",
    "version": "2.0.1"
  },
  {
    "name": "decode-named-character-reference",
    "version": "1.3.0"
  },
  {
    "name": "unist-util-stringify-position",
    "version": "4.0.0"
  },
  {
    "name": "mdast-util-gfm-autolink-literal",
    "version": "2.0.1"
  },
  {
    "name": "mdast-util-gfm-footnote",
    "version": "2.1.0"
  },
  {
    "name": "mdast-util-gfm-strikethrough",
    "version": "2.0.0"
  },
  {
    "name": "mdast-util-gfm-table",
    "version": "2.0.0"
  },
  {
    "name": "mdast-util-gfm-task-list-item",
    "version": "2.0.0"
  },
  {
    "name": "devlop",
    "version": "1.1.0"
  },
  {
    "name": "longest-streak",
    "version": "3.1.0"
  },
  {
    "name": "micromark-util-chunked",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-resolve-all",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-subtokenize",
    "version": "2.1.0"
  },
  {
    "name": "micromark-factory-destination",
    "version": "2.0.1"
  },
  {
    "name": "micromark-factory-label",
    "version": "2.0.1"
  },
  {
    "name": "micromark-factory-title",
    "version": "2.0.1"
  },
  {
    "name": "micromark-factory-whitespace",
    "version": "2.0.1"
  },
  {
    "name": "micromark-util-html-tag-name",
    "version": "2.0.1"
  },
  {
    "name": "@freddie/cordis",
    "version": "4.0.1"
  },
  {
    "name": "@freddie/cordis-plugin-loader",
    "version": "1.0.2"
  },
  {
    "name": "@freddie/freddie-client-ui-slots",
    "version": "0.1.1-rc.2"
  },
  {
    "name": "@freddie/freddie-client-ui-primitives",
    "version": "0.1.1-rc.2"
  },
  {
    "name": "oniguruma-to-es",
    "version": "4.3.6"
  },
  {
    "name": "character-entities",
    "version": "2.0.2"
  },
  {
    "name": "@freddie/cosmokit",
    "version": "1.8.2"
  },
  {
    "name": "html-void-elements",
    "version": "3.0.0"
  },
  {
    "name": "property-information",
    "version": "7.2.0"
  },
  {
    "name": "oniguruma-parser",
    "version": "0.12.2"
  },
  {
    "name": "regex",
    "version": "6.1.0"
  },
  {
    "name": "regex-recursion",
    "version": "6.0.2"
  },
  {
    "name": "ccount",
    "version": "2.0.1"
  },
  {
    "name": "mdast-util-find-and-replace",
    "version": "3.0.2"
  },
  {
    "name": "markdown-table",
    "version": "3.0.4"
  },
  {
    "name": "mdast-util-to-markdown",
    "version": "2.1.2"
  },
  {
    "name": "zwitch",
    "version": "2.0.4"
  },
  {
    "name": "regex-utilities",
    "version": "2.3.0"
  },
  {
    "name": "stringify-entities",
    "version": "4.0.4"
  },
  {
    "name": "comma-separated-tokens",
    "version": "2.0.3"
  },
  {
    "name": "space-separated-tokens",
    "version": "2.0.2"
  },
  {
    "name": "escape-string-regexp",
    "version": "5.0.0"
  },
  {
    "name": "unist-util-visit-parents",
    "version": "6.0.2"
  },
  {
    "name": "unist-util-is",
    "version": "6.0.1"
  },
  {
    "name": "hast-util-whitespace",
    "version": "3.0.0"
  },
  {
    "name": "mdast-util-phrasing",
    "version": "4.1.0"
  },
  {
    "name": "unist-util-visit",
    "version": "5.1.0"
  },
  {
    "name": "character-entities-legacy",
    "version": "3.0.0"
  },
  {
    "name": "character-entities-html4",
    "version": "2.1.0"
  }
]

export const importMapExact = {
  "zod": "/vendor/zod@4.4.3/index.js",
  "webjsx": "/vendor/webjsx@0.0.73/dist/index.js",
  "webjsx/jsx-runtime": "/vendor/webjsx@0.0.73/dist/jsx-runtime.js",
  "clsx": "/vendor/clsx@2.1.1/dist/clsx.mjs",
  "anser": "/vendor/anser@2.3.5/lib/index.js",
  "diff": "/vendor/diff@9.0.0/libesm/index.js",
  "katex": "/vendor/katex@0.16.47/dist/katex.mjs",
  "shiki/core": "/vendor/shiki@4.3.1/dist/core.mjs",
  "shiki/engine/javascript": "/vendor/shiki@4.3.1/dist/engine-javascript.mjs",
  "@shikijs/langs/typescript": "/vendor/@shikijs/langs@4.3.1/dist/typescript.mjs",
  "@shikijs/langs/shellscript": "/vendor/@shikijs/langs@4.3.1/dist/shellscript.mjs",
  "@shikijs/langs/json": "/vendor/@shikijs/langs@4.3.1/dist/json.mjs",
  "@shikijs/langs/python": "/vendor/@shikijs/langs@4.3.1/dist/python.mjs",
  "@shikijs/langs/ruby": "/vendor/@shikijs/langs@4.3.1/dist/ruby.mjs",
  "@shikijs/langs/go": "/vendor/@shikijs/langs@4.3.1/dist/go.mjs",
  "@shikijs/langs/rust": "/vendor/@shikijs/langs@4.3.1/dist/rust.mjs",
  "@shikijs/langs/java": "/vendor/@shikijs/langs@4.3.1/dist/java.mjs",
  "@shikijs/langs/c": "/vendor/@shikijs/langs@4.3.1/dist/c.mjs",
  "@shikijs/langs/cpp": "/vendor/@shikijs/langs@4.3.1/dist/cpp.mjs",
  "@shikijs/langs/csharp": "/vendor/@shikijs/langs@4.3.1/dist/csharp.mjs",
  "@shikijs/langs/kotlin": "/vendor/@shikijs/langs@4.3.1/dist/kotlin.mjs",
  "@shikijs/langs/swift": "/vendor/@shikijs/langs@4.3.1/dist/swift.mjs",
  "@shikijs/langs/php": "/vendor/@shikijs/langs@4.3.1/dist/php.mjs",
  "@shikijs/langs/yaml": "/vendor/@shikijs/langs@4.3.1/dist/yaml.mjs",
  "@shikijs/langs/toml": "/vendor/@shikijs/langs@4.3.1/dist/toml.mjs",
  "@shikijs/langs/ini": "/vendor/@shikijs/langs@4.3.1/dist/ini.mjs",
  "@shikijs/langs/markdown": "/vendor/@shikijs/langs@4.3.1/dist/markdown.mjs",
  "@shikijs/langs/mdx": "/vendor/@shikijs/langs@4.3.1/dist/mdx.mjs",
  "@shikijs/langs/html": "/vendor/@shikijs/langs@4.3.1/dist/html.mjs",
  "@shikijs/langs/css": "/vendor/@shikijs/langs@4.3.1/dist/css.mjs",
  "@shikijs/langs/scss": "/vendor/@shikijs/langs@4.3.1/dist/scss.mjs",
  "@shikijs/langs/less": "/vendor/@shikijs/langs@4.3.1/dist/less.mjs",
  "@shikijs/langs/sql": "/vendor/@shikijs/langs@4.3.1/dist/sql.mjs",
  "@shikijs/langs/xml": "/vendor/@shikijs/langs@4.3.1/dist/xml.mjs",
  "@shikijs/langs/lua": "/vendor/@shikijs/langs@4.3.1/dist/lua.mjs",
  "@tanstack/virtual-core": "/vendor/@tanstack/virtual-core@3.17.8/dist/esm/index.js",
  "mdast-util-from-markdown": "/vendor/mdast-util-from-markdown@2.0.3/index.js",
  "mdast-util-gfm": "/vendor/mdast-util-gfm@3.1.0/index.js",
  "mdast-util-math": "/vendor/mdast-util-math@3.0.0/index.js",
  "micromark-core-commonmark": "/vendor/micromark-core-commonmark@2.0.3/index.js",
  "micromark-extension-gfm": "/vendor/micromark-extension-gfm@3.0.0/index.js",
  "micromark-extension-math": "/vendor/micromark-extension-math@3.1.0/index.js",
  "micromark-factory-space": "/vendor/micromark-factory-space@2.0.1/index.js",
  "micromark-util-character": "/vendor/micromark-util-character@2.1.1/index.js",
  "micromark-util-classify-character": "/vendor/micromark-util-classify-character@2.0.1/index.js",
  "micromark-util-sanitize-uri": "/vendor/micromark-util-sanitize-uri@2.0.1/index.js",
  "micromark-util-symbol": "/vendor/micromark-util-symbol@2.0.1/lib/default.js",
  "micromark-util-types": "/vendor/micromark-util-types@2.0.2/index.js",
  "@freddie/freddie-client-web": "/vendor/@freddie/freddie-client-web@0.1.1-rc.2/src/index.js",
  "@shikijs/core": "/vendor/@shikijs/core@4.3.1/dist/index.mjs",
  "@shikijs/engine-javascript": "/vendor/@shikijs/engine-javascript@4.3.1/dist/index.mjs",
  "micromark-util-combine-extensions": "/vendor/micromark-util-combine-extensions@2.0.1/index.js",
  "micromark-extension-gfm-autolink-literal": "/vendor/micromark-extension-gfm-autolink-literal@2.1.0/index.js",
  "micromark-extension-gfm-footnote": "/vendor/micromark-extension-gfm-footnote@2.1.0/index.js",
  "micromark-extension-gfm-strikethrough": "/vendor/micromark-extension-gfm-strikethrough@2.1.0/index.js",
  "micromark-extension-gfm-table": "/vendor/micromark-extension-gfm-table@2.1.1/index.js",
  "micromark-extension-gfm-tagfilter": "/vendor/micromark-extension-gfm-tagfilter@2.0.0/index.js",
  "micromark-extension-gfm-task-list-item": "/vendor/micromark-extension-gfm-task-list-item@2.1.0/index.js",
  "micromark-util-encode": "/vendor/micromark-util-encode@2.0.1/index.js",
  "@shikijs/types": "/vendor/@shikijs/types@4.3.1/dist/index.mjs",
  "@shikijs/primitive": "/vendor/@shikijs/primitive@4.3.1/dist/index.mjs",
  "@shikijs/vscode-textmate": "/vendor/@shikijs/vscode-textmate@10.0.2/dist/index.js",
  "hast-util-to-html": "/vendor/hast-util-to-html@9.0.5/index.js",
  "mdast-util-to-string": "/vendor/mdast-util-to-string@4.0.0/index.js",
  "micromark": "/vendor/micromark@4.0.2/index.js",
  "micromark-util-decode-numeric-character-reference": "/vendor/micromark-util-decode-numeric-character-reference@2.0.2/index.js",
  "micromark-util-decode-string": "/vendor/micromark-util-decode-string@2.0.1/index.js",
  "micromark-util-normalize-identifier": "/vendor/micromark-util-normalize-identifier@2.0.1/index.js",
  "decode-named-character-reference": "/vendor/decode-named-character-reference@1.3.0/index.js",
  "unist-util-stringify-position": "/vendor/unist-util-stringify-position@4.0.0/index.js",
  "mdast-util-gfm-autolink-literal": "/vendor/mdast-util-gfm-autolink-literal@2.0.1/index.js",
  "mdast-util-gfm-footnote": "/vendor/mdast-util-gfm-footnote@2.1.0/index.js",
  "mdast-util-gfm-strikethrough": "/vendor/mdast-util-gfm-strikethrough@2.0.0/index.js",
  "mdast-util-gfm-table": "/vendor/mdast-util-gfm-table@2.0.0/index.js",
  "mdast-util-gfm-task-list-item": "/vendor/mdast-util-gfm-task-list-item@2.0.0/index.js",
  "devlop": "/vendor/devlop@1.1.0/lib/default.js",
  "longest-streak": "/vendor/longest-streak@3.1.0/index.js",
  "micromark-util-chunked": "/vendor/micromark-util-chunked@2.0.1/index.js",
  "micromark-util-resolve-all": "/vendor/micromark-util-resolve-all@2.0.1/index.js",
  "micromark-util-subtokenize": "/vendor/micromark-util-subtokenize@2.1.0/index.js",
  "micromark-factory-destination": "/vendor/micromark-factory-destination@2.0.1/index.js",
  "micromark-factory-label": "/vendor/micromark-factory-label@2.0.1/index.js",
  "micromark-factory-title": "/vendor/micromark-factory-title@2.0.1/index.js",
  "micromark-factory-whitespace": "/vendor/micromark-factory-whitespace@2.0.1/index.js",
  "micromark-util-html-tag-name": "/vendor/micromark-util-html-tag-name@2.0.1/index.js",
  "@freddie/cordis": "/vendor/@freddie/cordis@4.0.1/src/index.js",
  "@freddie/cordis-plugin-loader": "/vendor/@freddie/cordis-plugin-loader@1.0.2/src/index.js",
  "@freddie/freddie-client-ui-slots": "/vendor/@freddie/freddie-client-ui-slots@0.1.1-rc.2/src/index.js",
  "@freddie/freddie-client-ui-primitives": "/vendor/@freddie/freddie-client-ui-primitives@0.1.1-rc.2/src/index.js",
  "oniguruma-to-es": "/vendor/oniguruma-to-es@4.3.6/dist/esm/index.js",
  "character-entities": "/vendor/character-entities@2.0.2/index.js",
  "@freddie/cosmokit": "/vendor/@freddie/cosmokit@1.8.2/src/index.js",
  "html-void-elements": "/vendor/html-void-elements@3.0.0/index.js",
  "property-information": "/vendor/property-information@7.2.0/index.js",
  "oniguruma-parser/parser": "/vendor/oniguruma-parser@0.12.2/dist/parser/parse.js",
  "oniguruma-parser/traverser": "/vendor/oniguruma-parser@0.12.2/dist/traverser/traverse.js",
  "regex/internals": "/vendor/regex@6.1.0/src/internals.js",
  "regex-recursion": "/vendor/regex-recursion@6.0.2/src/index.js",
  "ccount": "/vendor/ccount@2.0.1/index.js",
  "mdast-util-find-and-replace": "/vendor/mdast-util-find-and-replace@3.0.2/index.js",
  "markdown-table": "/vendor/markdown-table@3.0.4/index.js",
  "mdast-util-to-markdown": "/vendor/mdast-util-to-markdown@2.1.2/index.js",
  "zwitch": "/vendor/zwitch@2.0.4/index.js",
  "regex-utilities": "/vendor/regex-utilities@2.3.0/src/index.js",
  "stringify-entities": "/vendor/stringify-entities@4.0.4/index.js",
  "comma-separated-tokens": "/vendor/comma-separated-tokens@2.0.3/index.js",
  "space-separated-tokens": "/vendor/space-separated-tokens@2.0.2/index.js",
  "escape-string-regexp": "/vendor/escape-string-regexp@5.0.0/index.js",
  "unist-util-visit-parents": "/vendor/unist-util-visit-parents@6.0.2/index.js",
  "unist-util-is": "/vendor/unist-util-is@6.0.1/index.js",
  "hast-util-whitespace": "/vendor/hast-util-whitespace@3.0.0/index.js",
  "mdast-util-phrasing": "/vendor/mdast-util-phrasing@4.1.0/index.js",
  "unist-util-visit-parents/do-not-use-color": "/vendor/unist-util-visit-parents@6.0.2/lib/color.node.js",
  "unist-util-visit": "/vendor/unist-util-visit@5.1.0/index.js",
  "character-entities-legacy": "/vendor/character-entities-legacy@3.0.0/index.js",
  "character-entities-html4": "/vendor/character-entities-html4@2.1.0/index.js",
  "node:module": "/vendor/node-module-stub.js"
}

export const importMapPrefix = {}

export const cssLinks = [
  "/vendor/katex@0.16.47/dist/katex.min.css"
]
