const css = {
  root: 'freddie-workflowRunPanel__root',
  runHeader: 'freddie-workflowRunPanel__runHeader',
  runLeading: 'freddie-workflowRunPanel__runLeading',
  runTitle: 'freddie-workflowRunPanel__runTitle',
  runSummary: 'freddie-workflowRunPanel__runSummary',
  statusTail: 'freddie-workflowRunPanel__statusTail',
  phaseHeader: 'freddie-workflowRunPanel__phaseHeader',
  phaseLeading: 'freddie-workflowRunPanel__phaseLeading',
  phaseTitle: 'freddie-workflowRunPanel__phaseTitle',
  phaseCount: 'freddie-workflowRunPanel__phaseCount',
  phaseStatus: 'freddie-workflowRunPanel__phaseStatus',
  separator: 'freddie-workflowRunPanel__separator',
  phaseList: 'freddie-workflowRunPanel__phaseList',
  phase: 'freddie-workflowRunPanel__phase',
  progress: 'freddie-workflowRunPanel__progress',
  progressLabel: 'freddie-workflowRunPanel__progressLabel',
  currentPhase: 'freddie-workflowRunPanel__currentPhase',
  currentPhaseName: 'freddie-workflowRunPanel__currentPhaseName',
  declaredPhases: 'freddie-workflowRunPanel__declaredPhases',
  declaredPhase: 'freddie-workflowRunPanel__declaredPhase',
  logDetails: 'freddie-workflowRunPanel__logDetails',
  logSummary: 'freddie-workflowRunPanel__logSummary',
  logs: 'freddie-workflowRunPanel__logs',
  logLine: 'freddie-workflowRunPanel__logLine',
  members: 'freddie-workflowRunPanel__members',
  memberRow: 'freddie-workflowRunPanel__memberRow',
  memberButton: 'freddie-workflowRunPanel__memberButton',
  dotSlot: 'freddie-workflowRunPanel__dotSlot',
  memberLabelWrap: 'freddie-workflowRunPanel__memberLabelWrap',
  memberLabel: 'freddie-workflowRunPanel__memberLabel',
  memberStatus: 'freddie-workflowRunPanel__memberStatus',
  empty: 'freddie-workflowRunPanel__empty',
}

export default css
