import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import os from 'node:os'

const TEST_HOME = path.join(os.tmpdir(), 'freddie-test-' + Date.now())
process.env.FREDDIE_HOME = TEST_HOME; process.env.FREDDIE_PROFILES_ROOT = path.join(TEST_HOME, 'profiles')
fs.mkdirSync(path.join(TEST_HOME, 'profiles'), { recursive: true })

const results = []
const T = async (n, fn) => { try { await fn(); results.push([n, 'OK']) } catch (e) { results.push([n, 'FAIL: ' + (e?.stack || e?.message || e)]) } }

await T('home+config+skin', async () => {
    assert.equal((await import('./src/home.js')).getFreddieHome(), TEST_HOME)
    const c = await import('./src/config.js'); c.saveConfigValue('display.skin', 'ares'); assert.equal(c.getConfigValue('display.skin'), 'ares')
    const s = await import('./src/skin/engine.js'); for (const n of ['default','ares','mono','slate']) assert.ok(s.listBuiltinSkins().includes(n))
    s.setActiveSkin('mono'); assert.equal(s.getActiveSkin().name, 'mono')
})
await T('sessions+FTS5', async () => {
    const { createSession, appendMessage, getMessages, search } = await import('./src/sessions.js')
    const sid = await createSession({ platform: 'cli' })
    for (const t of ['banana smoothie', 'sounds delicious', 'recipe please']) await appendMessage(sid, { role: 'user', content: t })
    assert.equal((await getMessages(sid)).length, 3); assert.ok((await search('banana')).length >= 1)
})
await T('tools+toolsets', async () => {
    const { registry, discoverBuiltinTools } = await import('./src/tools/registry.js'); await discoverBuiltinTools()
    const names = registry.list().map(t => t.name); assert.ok(names.length >= 50)
    for (const n of 'bash,read,write,edit,grep,todo,memory,delegate,browser,approval,checkpoint,clarify,code_execution,cronjob,send_message,session_search,terminal,skill_manager,vision,tts,mixture_of_agents,osv_check,schema_sanitizer,mcp_tool,file_operations,patch_parser,tool_output_limits,file_state,skill_usage'.split(',')) assert.ok(names.includes(n), n)
    const D = (n, a) => registry.dispatch(n, a).then(r => { try { return JSON.parse(r) } catch { return r } }); const tf = path.join(TEST_HOME, 'tf.txt'); const tf2 = path.join(TEST_HOME, 'tf2.txt')
    assert.match((await D('bash', { command: 'echo hi-freddie', timeout_ms: 5000 })).stdout, /hi-freddie/)
    await D('write', { path: tf, content: 'alpha\nbeta\ngamma' }); assert.match(JSON.stringify(await D('read', { path: tf })), /beta/)
    await D('edit', { path: tf, old_string: 'beta', new_string: 'BETA' }); assert.match(JSON.stringify(await D('grep', { pattern: 'BETA', path: TEST_HOME })), /BETA/)
    await D('todo', { action: 'add', content: 'task-x' }); assert.match(JSON.stringify(await D('todo', { action: 'list' })), /task-x/)
    await D('checkpoint', { action: 'save', name: 'cp1', data: { v: 1 } }); assert.equal((await D('checkpoint', { action: 'load', name: 'cp1' })).data.v, 1)
    await D('memory', { action: 'add', content: 'mem-x' }); assert.match(JSON.stringify(await D('memory', { action: 'list' })), /mem-x/)
    await D('file_state', { action: 'record', session_id: 's1', file_path: tf, op: 'write' }); assert.match(JSON.stringify(await D('file_state', { action: 'list', session_id: 's1' })), /tf\.txt/)
    await D('file_operations', { action: 'copy', src: tf, dest: tf2 }); assert.ok(fs.existsSync(tf2)); assert.ok((await D('skill_usage', { action: 'record', name: 'sk' })).recorded)
    const ts = await import('./src/toolsets.js'); assert.ok((await ts.getEnabledToolSchemas(['core'])).length >= ts._FREDDIE_CORE_TOOLS.length)
})
await T('agent-machine', async () => {
    const { runTurn } = await import('./src/agent/machine.js')
    const echo = async ({ messages }) => ({ content: 'echo: ' + (messages[messages.length - 1]?.content || ''), tool_calls: [] })
    assert.match((await runTurn({ prompt: 'ping', callLLM: echo, timeoutMs: 5000 })).messages[1].content, /ping/)
    let phase = 0
    const callLLM = async () => phase++ === 0 ? { content: '', tool_calls: [{ id: 'c1', name: 'bash', arguments: { command: 'echo loop-ok', timeout_ms: 5000 } }] } : { content: 'done', tool_calls: [] }
    const out = await runTurn({ prompt: 'use tool', callLLM, timeoutMs: 10000 })
    assert.equal(out.result, 'done'); assert.match(out.messages.find(m => m.role === 'tool').content, /loop-ok/)
    const { resolveCallLLM } = await import('./src/agent/llm_resolver.js')
    const { isReachable } = await import('./src/agent/acptoapi-bridge.js')
    if (await isReachable()) {
        const real = resolveCallLLM({ model: 'claude/haiku' })
        const r = await real({ messages: [{ role: 'user', content: 'reply with exactly: REAL_OK' }], tools: [] })
        assert.match(r.content, /REAL_OK/)
    }
})
await T('gateway+platforms+hooks', async () => {
    const { Gateway } = await import('./src/gateway/run.js')
    const { WebhookAdapter } = await import('./src/gateway/platforms/webhook.js')
    const { registerBuiltinHooks } = await import('./src/gateway/builtin_hooks/index.js')
    const wh = new WebhookAdapter({ port: 0 })
    const gw = new Gateway({ platforms: { webhook: wh } })
    registerBuiltinHooks(gw); assert.ok(gw.hooks.inbound.length >= 4)
    const got = new Promise(r => wh.once('message', () => r()))
    await gw.start()
    const res = await fetch(`http://127.0.0.1:${wh.port}/webhook`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ from: 't', text: 'x' }) })
    assert.equal(res.status, 200); await got; await gw.stop()
    const dir = path.resolve('src/gateway/platforms')
    for (const s of ['telegram','discord','slack','whatsapp','signal','matrix','mattermost','email','sms','dingtalk','wecom','weixin','feishu','qqbot','bluebubbles','homeassistant']) {
        const txt = fs.readFileSync(path.join(dir, s + '.js'), 'utf8')
        assert.ok(!txt.includes('not implemented'), s)
        const cls = s.charAt(0).toUpperCase() + s.slice(1) + 'Adapter'
        const inst = new (await import(`file://${path.join(dir, s + '.js').replace(/\\/g, '/')}`))[cls]({})
        assert.ok(Array.isArray(inst.getRequiredEnv()))
    }
})
await T('acp-full', async () => {
    const { AcpServer } = await import('./src/acp/server.js'); const { Readable, Writable } = await import('node:stream')
    const out = []; const w = new Writable({ write(c, _, cb) { out.push(c.toString()); cb() } }); const r = new Readable({ read() {} })
    const srv = new AcpServer({ stdin: r, stdout: w }); srv.start()
    r.push(JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize' }) + '\n')
    r.push(JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tool.list' }) + '\n')
    await new Promise(x => setTimeout(x, 300))
    const lines = out.join('').trim().split('\n').map(l => JSON.parse(l))
    assert.equal(lines[0].result.name, 'freddie'); assert.ok(lines[0].result.events.includes('tool.start'))
    assert.ok(lines[1].result.tools.length >= 50); srv.stop()
    const { Events } = await import('./src/acp/events.js')
    const sent = []; Events.toolStart((o) => sent.push(o), { name: 't' }); assert.equal(sent[0].method, 'event/tool.start')
    const { checkPermission, rememberAllow, resetForTests } = await import('./src/acp/permissions.js')
    resetForTests(); assert.equal(checkPermission('s1', 'bash'), 'ask'); rememberAllow('s1', 'bash'); assert.equal(checkPermission('s1', 'bash'), 'allow')
})
await T('plugins+memory', async () => {
    const { PluginManager } = await import('./src/plugins/manager.js')
    const pm = new PluginManager(); let fired = 0
    pm.register({ name: 'noop', register: (ctx) => ctx.registerHook('preToolCall', async p => { fired++; return p }) })
    await pm.invoke('preToolCall', { name: 'bash' }); assert.equal(fired, 1)
    const { listMemoryProviders, createMemoryProvider } = await import('./src/plugins/memory/provider.js')
    for (const n of ['honcho','mem0','holographic','retaindb']) assert.ok(listMemoryProviders().includes(n))
    const holo = createMemoryProvider('holographic', {})
    await holo.syncTurn([{ role: 'user', content: 'test' }]); assert.ok((await holo.prefetch('test')).items.length >= 1)
    const { metricsText, inc } = await import('./src/plugins/observability/index.js')
    inc('test_counter', 7); assert.match(metricsText(), /freddie_counter\{name="test_counter"\} 7/)
    const { award, listAchievements } = await import('./src/plugins/achievements/index.js')
    await award('test-award'); assert.ok((await listAchievements()).some(a => a.name === 'test-award'))
})
await T('profiles+observability+auth+env+context+cron+batch+slash+skills', async () => {
    const cr = await import('./src/commands/registry.js')
    assert.ok(cr.COMMAND_REGISTRY.length >= 10 && cr.resolveCommand('/bg') === 'background' && cr.gatewayHelpLines().length >= 5 && cr.slackAppManifest().features.slash_commands[0].command.startsWith('/') && cr.discordSkillCommands().length >= 1)
    const cm = await import('./src/cli/completer.js'); assert.ok(new cm.SlashCommandCompleter().suggest('/ba')[0].value === '/background' && new cm.FuzzyMatcher(['anthropic','openrouter','xai']).match('or')[0] === 'openrouter' && typeof cm.createCompleter().suggest === 'function')
    const sd = path.join(TEST_HOME, 'skills', 'fixture'); fs.mkdirSync(sd, { recursive: true })
    fs.writeFileSync(path.join(sd, 'SKILL.md'), '---\nname: fixture\ndescription: t\n---\nbody')
    const { listSkills, findSkill, skillAsUserMessage } = await import('./src/skills/index.js')
    assert.ok(listSkills().find(s => s.name === 'fixture') && findSkill('fixture').description === 't' && /\[skill:fixture\]/.test(skillAsUserMessage('fixture', 'arg').content) && listSkills([path.resolve('skills')]).length >= 3)
    const pm = await import('./src/commands/profile.js')
    pm.createProfile('coder'); pm.renameProfile('coder', 'devops'); assert.ok(pm.listAllProfiles().includes('devops'))
    fs.writeFileSync(path.join(TEST_HOME, 'profiles', 'devops', 'config.yaml'), 'agent:\n  provider: anthropic\n')
    const exp = pm.exportProfile('devops', TEST_HOME); pm.deleteProfile('devops'); pm.importProfile(exp, 'imported'); assert.ok(pm.listAllProfiles().includes('imported')); pm.deleteProfile('imported')
    const ob = await import('./src/observability/debug.js'); (await import('./src/observability/log.js')).log({ subsystem: 'unit', severity: 'info', msg: 'h' })
    ob.registerDebug('unit', () => ({ ok: 1 })); assert.ok(ob.listDebug().includes('unit')); assert.equal(ob.snapshot('unit').ok, 1)
    const au = await import('./src/auth.js')
    await au.getAuthStore().setCredential('test', { key: 'abc' }); assert.equal((await au.getAuthStore().getCredential('test')).value.key, 'abc')
    assert.ok(au.isKnownAuthProvider('anthropic') && au.envForProvider('openai') === 'OPENAI_API_KEY' && au.isExpiring({ expires_at: Math.floor(Date.now() / 1000) - 1 })); assert.match(au.tokenFingerprint('abcdef1234567890'), /abcd…7890/)
    const cv = await import('./src/config.js'); assert.ok(Array.isArray(cv.validateConfigStructure({}))); assert.equal(cv.expandEnvVars('${HOME_X_NA}'), '')
    const sv = await import('./src/gateway/service.js'), oe = await import('./src/agent/oauth_endpoints.js'); assert.ok(sv.getRuntimeSnapshot().serviceName.startsWith('freddie-gateway') && /Environment=K=V/.test(sv.renderSystemdUnit({ execStart: 'x', envVars: { K: 'V' } })) && oe.resolveKimiBaseUrl().includes('moonshot') && oe.resolveZaiBaseUrl({ endpoint: 'https://api.z.ai' }).includes('z.ai') && oe.isCodexAccessTokenExpiring('bad.jwt'))
    const fix = path.join(TEST_HOME, 'fix'); fs.mkdirSync(fix, { recursive: true }); fs.writeFileSync(path.join(fix, '.freddie-context'), 'hello-ctx')
    assert.ok((await (await import('./src/context/engine.js')).buildContext({ plugins: ['file'], options: { cwd: fix } })).find(b => b.body.includes('hello-ctx')))
    const cp = await import('./src/cron/cron-parse.js'); assert.ok(cp.matches(cp.parseCron('* * * * *'), new Date()))
    const sch = await import('./src/cron/scheduler.js'); const id = await sch.createJob({ cron: '*/5 * * * *', prompt: 'tick' }); assert.ok((await sch.listJobs()).some(j => j.id === id)); await sch.deleteJob(id)
    assert.equal((await (await import('./src/batch.js')).runBatch({ prompts: ['a', 'b', 'c'], concurrency: 2 })).results.length, 3)
})
await T('utils+time+redact+model-meta+agent-helpers', async () => {
    const u = await import('./src/utils.js')
    assert.equal(u.ansiStrip('\x1b[31mhi\x1b[0m'), 'hi'); assert.match(u.redactSecret('Bearer sk-1234567890abcdefghij'), /\[REDACTED\]/)
    let n = 0; assert.equal(await u.retry({ fn: async () => { if (n++ < 1) throw new Error('x'); return 'ok' }, attempts: 3, backoff: 1 }), 'ok')
    assert.equal((await import('./src/time.js')).parseDuration('5m'), 300_000)
    assert.match((await import('./src/agent/redact.js')).redactSensitive('sk-ant-1234567890abcdefghij'), /\[REDACTED\]/)
    const mm = await import('./src/agent/model_metadata.js'); assert.ok(mm.getModelContextLength('claude-opus-4-7') > mm.MINIMUM_CONTEXT_LENGTH)
    assert.equal((await import('./src/agent/image_routing.js')).routeImagesNative([{ role: 'user', content: [{ type: 'image_url', image_url: { url: 'data:image/png;base64,abc' } }] }], 'anthropic')[0].content[0].type, 'image')
    assert.equal((await import('./src/agent/error_classifier.js')).classifyError({ message: 'rate limit 429' }).kind, 'rate_limit')
    assert.ok(!(await import('./src/agent/file_safety.js')).checkFileSafety('/etc/passwd').safe)
    assert.match((await import('./src/agent/title_generator.js')).generateTitle('hello world there'), /Hello/)
    assert.ok((await import('./src/agent/usage_pricing.js')).calculateCost({ model: 'claude-sonnet-4-6', prompt_tokens: 1_000_000, completion_tokens: 0 }) > 0)
    let m = 0; assert.equal(await (await import('./src/agent/retry_utils.js')).retryAsync(async () => { if (m++ < 1) throw new Error('rate limit 429'); return 'done' }, { attempts: 3, backoff: 1 }), 'done')
    const pc = await import('./src/agent/prompt_caching.js'); assert.ok(pc.countBreakpoints(pc.annotateBreakpoints([{ role: 'system', content: 's' }, { role: 'user', content: 'u' }])) >= 1)
    for (const [f, k] of [['anthropic_adapter','chat'],['bedrock_adapter','chat'],['codex_responses_adapter','chat'],['auxiliary_client','call_llm'],['gemini_native_adapter','chat'],['gemini_cloudcode_adapter','chat'],['google_oauth','getToken'],['google_code_assist','complete'],['image_gen_provider','generate'],['image_gen_registry','generateAndRecord']]) assert.equal(typeof (await import('./src/agent/' + f + '.js'))[k], 'function', f)
})
await T('mcp+swe+distributions+account+credpool', async () => {
    const { McpServer } = await import('./src/mcp/server.js'); const { Readable, Writable } = await import('node:stream')
    const out = []; const w = new Writable({ write(c, _, cb) { out.push(c.toString()); cb() } }); const r = new Readable({ read() {} })
    const srv = new McpServer({ stdin: r, stdout: w }); srv.start()
    r.push(JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'initialize' }) + '\n')
    r.push(JSON.stringify({ jsonrpc: '2.0', id: 2, method: 'tools/list' }) + '\n')
    await new Promise(x => setTimeout(x, 400))
    const lines = out.join('').trim().split('\n').map(l => JSON.parse(l))
    assert.equal(lines[0].result.serverInfo.name, 'freddie-mcp'); assert.ok(lines[1].result.tools.length >= 50); srv.stop()
    const { runMiniSwe } = await import('./src/swe/runner.js')
    const swe = await runMiniSwe({ task: { prompt: 'hi' }, timeoutMs: 5000, callLLM: async () => ({ content: 'ok', tool_calls: [] }) })
    assert.ok(typeof swe.passed === 'boolean')
    const { listDistributions, getDistribution } = await import('./src/toolset_distributions.js')
    assert.ok(listDistributions().length >= 3); assert.ok(getDistribution('coder').enabledToolsets.includes('core'))
    const { record, totalLifetime } = await import('./src/agent/account_usage.js')
    await record({ sessionId: 't', model: 'm', promptTokens: 10, completionTokens: 5, costUsd: 0.01 })
    assert.ok((await totalLifetime()).prompt >= 10)
    const cp = await import('./src/agent/credential_pool.js')
    cp.resetForTests(); process.env.TESTPROVIDER_API_KEYS = 'k1,k2,k3'
    assert.ok(['k1','k2','k3'].includes(cp.next('testprovider')))
})
await T('compressor+trajectory', async () => {
    const { compress, shouldCompress, SUMMARY_PREFIX } = await import('./src/agent/compress/index.js')
    const long = Array.from({ length: 60 }, (_, i) => ({ role: i % 2 === 0 ? 'user' : 'assistant', content: 'msg-' + i + ' '.repeat(800) }))
    assert.equal(shouldCompress({ messages: long, modelContextLength: 1000 }), true)
    const callLLM = async () => ({ content: '## Active Task\nfoo', tool_calls: [] })
    const out = await compress({ messages: long, modelContextLength: 1000, callLLM })
    assert.equal(out.didCompress, true); assert.ok(out.compressedMessages.some(m => typeof m.content === 'string' && m.content.startsWith(SUMMARY_PREFIX)))
    const { compressTrajectory } = await import('./src/agent/trajectory.js')
    assert.ok(compressTrajectory({ messages: long, maxKeep: 5 }).compressed.length < long.length)
})
await T('env+pi+cli+tui+setup+website+helpers', async () => {
    const envs = await import('./src/tools/environments/index.js'); assert.match((await envs.createEnvironment('local', {}).run('echo env-ok')).stdout, /env-ok/)
    for (const n of ['local','docker','ssh','modal','managed_modal','daytona','singularity','vercel_sandbox']) assert.ok(envs.listEnvironments().includes(n) && typeof envs.syncTo === 'function', n)
    const su = await import('./src/cli/setup.js'); for (const fn of ['setupWizard','setupModelProvider','setupTerminalBackend','setupTts','setupGatewayPlatform','setupAgentSettings','setupSkin','getSetupStatus']) assert.equal(typeof su[fn], 'function', fn)
    for (const m of ['./src/agent/pi-bridge.js','./src/cli/interactive.js','./src/tui/index.js','./src/cli/main.js']) { const mm = await import(m); assert.ok(Object.values(mm).some(v => typeof v === 'function'), m) }
    assert.match((await import('./src/cli/colors.js')).fg.red('hi'), /\x1b\[31m/); assert.equal((await import('./src/cli/model_normalize.js')).normalizeModel('sonnet'), 'claude-sonnet-4-6')
    const wh = await import('./src/gateway/helpers.js'); assert.ok((await import('./src/cli/model_catalog.js')).listCatalog().length >= 5 && (await import('./src/cli/doctor.js')).runDoctor().some(c => c.name === 'node-version') && wh.hmacVerify('s', 'b', wh.hmacSign('s', 'b')))
    assert.ok((await (await import('./src/acp/auth.js')).authenticateRequest({})).ok && (await (await import('./src/acp/tools.js')).listToolsForAcp()).length >= 50)
    const wh2 = fs.readFileSync(path.join('website', 'docs/index.html'), 'utf8'); for (const m of ['ds-hero-title', 'rail-green', 'when do I reach']) assert.ok(wh2.includes(m), m)
    const dash = await (await import('./src/web/server.js')).createDashboard({ port: 0 })
    const sse = await fetch(dash.url + 'api/chat', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ prompt: 'ping-from-test' }) })
    assert.equal(sse.status, 200); assert.match(sse.headers.get('content-type') || '', /event-stream/)
    const txt = await sse.text(); assert.match(txt, /event: (start|done|error|message)/)
    const html = await (await fetch(dash.url + 'index.html')).text()
    assert.match(html, /anentrypoint-design/); await dash.stop()
})

console.log('\n=== test.js results ===')
for (const [n, s] of results) console.log(`  ${s.startsWith('OK') ? '✓' : '✗'} ${n}\t${s}`)
const failed = results.filter(r => !r[1].startsWith('OK'))
try { (await import('./src/sessions.js')).closeDb() } catch {}; try { (await import('./src/observability/log.js')).closeAll() } catch {}
if (failed.length) { console.error(`\n${failed.length} FAILED`); process.exit(1) }
console.log(`\n${results.length} passed`)
await new Promise(r => setTimeout(r, 100)); process.exit(0)
