const css = {
  root: 'freddie-modelSelect__root',
  trigger: 'freddie-modelSelect__trigger',
  triggerLabel: 'freddie-modelSelect__triggerLabel',
  triggerEffort: 'freddie-modelSelect__triggerEffort',
  chevron: 'freddie-modelSelect__chevron',
  chevronOpen: 'freddie-modelSelect__chevronOpen',
  menu: 'freddie-modelSelect__menu',
  status: 'freddie-modelSelect__status',
  empty: 'freddie-modelSelect__empty',
  error: 'freddie-modelSelect__error',
  warning: 'freddie-modelSelect__warning',
  retry: 'freddie-modelSelect__retry',
  groups: 'freddie-modelSelect__groups',
  group: 'freddie-modelSelect__group',
  groupTitle: 'freddie-modelSelect__groupTitle',
  option: 'freddie-modelSelect__option',
  selected: 'freddie-modelSelect__selected',
  optionCopy: 'freddie-modelSelect__optionCopy',
  modelName: 'freddie-modelSelect__modelName',
  description: 'freddie-modelSelect__description',
  check: 'freddie-modelSelect__check',
  cell: 'freddie-modelSelect__cell',
  cellLabel: 'freddie-modelSelect__cellLabel',
  cellValue: 'freddie-modelSelect__cellValue',
  cellChevron: 'freddie-modelSelect__cellChevron',
}
export default css
