const css = {
  card: 'freddie-subagentCard__card',
  cardOpen: 'freddie-subagentCard__cardOpen',
  header: 'freddie-subagentCard__header',
  headText: 'freddie-subagentCard__headText',
  name: 'freddie-subagentCard__name',
  description: 'freddie-subagentCard__description',
  chevron: 'freddie-subagentCard__chevron',
  chevronOpen: 'freddie-subagentCard__chevronOpen',
  pending: 'freddie-subagentCard__pending',
  body: 'freddie-subagentCard__body',
  readOnly: 'freddie-subagentCard__readOnly',
  field: 'freddie-subagentCard__field',
  head: 'freddie-subagentCard__head',
  label: 'freddie-subagentCard__label',
  badges: 'freddie-subagentCard__badges',
  badge: 'freddie-subagentCard__badge',
  reset: 'freddie-subagentCard__reset',
  input: 'freddie-subagentCard__input',
  inputInvalid: 'freddie-subagentCard__inputInvalid',
  hint: 'freddie-subagentCard__hint',
  invalid: 'freddie-subagentCard__invalid',
  footer: 'freddie-subagentCard__footer',
  failed: 'freddie-subagentCard__failed',
  discard: 'freddie-subagentCard__discard',
  save: 'freddie-subagentCard__save',
}

export default css
