const css = {
  dialog: 'freddie-shortcutReference__dialog',
  contents: 'freddie-shortcutReference__contents',
  header: 'freddie-shortcutReference__header',
  title: 'freddie-shortcutReference__title',
  close: 'freddie-shortcutReference__close',
  searchRow: 'freddie-shortcutReference__searchRow',
  search: 'freddie-shortcutReference__search',
  list: 'freddie-shortcutReference__list',
  group: 'freddie-shortcutReference__group',
  rows: 'freddie-shortcutReference__rows',
  row: 'freddie-shortcutReference__row',
  rowFixed: 'freddie-shortcutReference__rowFixed',
  label: 'freddie-shortcutReference__label',
  binding: 'freddie-shortcutReference__binding',
  keyBadge: 'freddie-shortcutReference__keyBadge',
  fixedKey: 'freddie-shortcutReference__fixedKey',
  unbound: 'freddie-shortcutReference__unbound',
  editor: 'freddie-shortcutReference__editor',
  action: 'freddie-shortcutReference__action',
  recorder: 'freddie-shortcutReference__recorder',
  recorderInvalid: 'freddie-shortcutReference__recorderInvalid',
  footer: 'freddie-shortcutReference__footer',
  status: 'freddie-shortcutReference__status',
  statusError: 'freddie-shortcutReference__statusError',
  hint: 'freddie-shortcutReference__hint',
}
export default css
