const css = {
  section: 'freddie-agentPresetSection__section',
  title: 'freddie-agentPresetSection__title',
  intro: 'freddie-agentPresetSection__intro',
  group: 'freddie-agentPresetSection__group',
  groupHead: 'freddie-agentPresetSection__groupHead',
  cards: 'freddie-agentPresetSection__cards',
  card: 'freddie-agentPresetSection__card',
  cardActive: 'freddie-agentPresetSection__cardActive',
  cardBroken: 'freddie-agentPresetSection__cardBroken',
  brokenBadge: 'freddie-agentPresetSection__brokenBadge',
  cardBrokenReason: 'freddie-agentPresetSection__cardBrokenReason',
  cardMain: 'freddie-agentPresetSection__cardMain',
  cardHead: 'freddie-agentPresetSection__cardHead',
  cardName: 'freddie-agentPresetSection__cardName',
  badge: 'freddie-agentPresetSection__badge',
  inUse: 'freddie-agentPresetSection__inUse',
  cardDesc: 'freddie-agentPresetSection__cardDesc',
  cardId: 'freddie-agentPresetSection__cardId',
  cardFoot: 'freddie-agentPresetSection__cardFoot',
  iconButton: 'freddie-agentPresetSection__iconButton',
  iconDanger: 'freddie-agentPresetSection__iconDanger',
  revealedPath: 'freddie-agentPresetSection__revealedPath',
  revealedPathLabel: 'freddie-agentPresetSection__revealedPathLabel',
  secondaryButton: 'freddie-agentPresetSection__secondaryButton',
  field: 'freddie-agentPresetSection__field',
  fieldLabel: 'freddie-agentPresetSection__fieldLabel',
  input: 'freddie-agentPresetSection__input',
  dialog: 'freddie-agentPresetSection__dialog',
  dialogFields: 'freddie-agentPresetSection__dialogFields',
  viewerCode: 'freddie-agentPresetSection__viewerCode',
  error: 'freddie-agentPresetSection__error',
  deleteDialog: 'freddie-agentPresetSection__deleteDialog',
  deleteConfirm: 'freddie-agentPresetSection__deleteConfirm',
  creatorButton: 'freddie-agentPresetSection__creatorButton',
}
export default css
