const css = {
  root: 'freddie-workspaceBrowser__root',
  rail: 'freddie-workspaceBrowser__rail',
  iconButton: 'freddie-workspaceBrowser__iconButton',
  sectionHeader: 'freddie-workspaceBrowser__sectionHeader',
  sectionLabel: 'freddie-workspaceBrowser__sectionLabel',
  sectionLabelHidden: 'freddie-workspaceBrowser__sectionLabelHidden',
  searchSlot: 'freddie-workspaceBrowser__searchSlot',
  searchSlotExpanded: 'freddie-workspaceBrowser__searchSlotExpanded',
  headerActions: 'freddie-workspaceBrowser__headerActions',
  headerActionsHidden: 'freddie-workspaceBrowser__headerActionsHidden',
  search: 'freddie-workspaceBrowser__search',
  searchExpanded: 'freddie-workspaceBrowser__searchExpanded',
  searchButton: 'freddie-workspaceBrowser__searchButton',
  searchInput: 'freddie-workspaceBrowser__searchInput',
  clearButton: 'freddie-workspaceBrowser__clearButton',
  listArea: 'freddie-workspaceBrowser__listArea',
  treeBody: 'freddie-workspaceBrowser__treeBody',
  fade: 'freddie-workspaceBrowser__fade',
  wide: 'freddie-workspaceBrowser__wide',
  list: 'freddie-workspaceBrowser__list',
  flatList: 'freddie-workspaceBrowser__flatList',
  searchTree: 'freddie-workspaceBrowser__searchTree',
  groupSection: 'freddie-workspaceBrowser__groupSection',
  searchStatus: 'freddie-workspaceBrowser__searchStatus',
  searchWarning: 'freddie-workspaceBrowser__searchWarning',
  listTopDropIndicator: 'freddie-workspaceBrowser__listTopDropIndicator',
  listTopDropActive: 'freddie-workspaceBrowser__listTopDropActive',
  workspaceDropBefore: 'freddie-workspaceBrowser__workspaceDropBefore',
  workspaceDropAfter: 'freddie-workspaceBrowser__workspaceDropAfter',
  sessionOverflowButton: 'freddie-workspaceBrowser__sessionOverflowButton',
  empty: 'freddie-workspaceBrowser__empty',
  renameInput: 'freddie-workspaceBrowser__renameInput',
  renameError: 'freddie-workspaceBrowser__renameError',
  deleteAction: 'freddie-workspaceBrowser__deleteAction',
  deleteStatus: 'freddie-workspaceBrowser__deleteStatus',
}

export default css
