const css = {
  frame: 'freddie-questionComposer__frame',
  card: 'freddie-questionComposer__card',
  cardMinimized: 'freddie-questionComposer__cardMinimized',
  headerActions: 'freddie-questionComposer__headerActions',
  header: 'freddie-questionComposer__header',
  headingBlock: 'freddie-questionComposer__headingBlock',
  eyebrow: 'freddie-questionComposer__eyebrow',
  title: 'freddie-questionComposer__title',
  detail: 'freddie-questionComposer__detail',
  footerActions: 'freddie-questionComposer__footerActions',
  pager: 'freddie-questionComposer__pager',
  progress: 'freddie-questionComposer__progress',
  iconButton: 'freddie-questionComposer__iconButton',
  body: 'freddie-questionComposer__body',
  options: 'freddie-questionComposer__options',
  option: 'freddie-questionComposer__option',
  optionSelected: 'freddie-questionComposer__optionSelected',
  number: 'freddie-questionComposer__number',
  checkbox: 'freddie-questionComposer__checkbox',
  checkboxChecked: 'freddie-questionComposer__checkboxChecked',
  optionCopy: 'freddie-questionComposer__optionCopy',
  optionLine: 'freddie-questionComposer__optionLine',
  optionLabel: 'freddie-questionComposer__optionLabel',
  badge: 'freddie-questionComposer__badge',
  description: 'freddie-questionComposer__description',
  customRow: 'freddie-questionComposer__customRow',
  customRowActive: 'freddie-questionComposer__customRowActive',
  field: 'freddie-questionComposer__field',
  fieldMirror: 'freddie-questionComposer__fieldMirror',
  fieldInput: 'freddie-questionComposer__fieldInput',
  customInline: 'freddie-questionComposer__customInline',
  customBlock: 'freddie-questionComposer__customBlock',
  footer: 'freddie-questionComposer__footer',
  feedback: 'freddie-questionComposer__feedback',
}

export default css
