export const REMOTE_STREAM_NAMESPACE = 'stream'

export const REMOTE_STREAM_MAX_POLL_MS = 20_000

export const REMOTE_STREAM_MAX_OPEN_STREAMS = 128

export const REMOTE_STREAM_MAX_BUFFERED_FRAMES = 256

export const REMOTE_STREAM_MAX_FRAMES_PER_POLL = 64

export const REMOTE_STREAM_IDLE_TIMEOUT_MS = 30_000
