const css = {
  card: 'freddie-cordisDefineRow__card',
  title: 'freddie-cordisDefineRow__title',
  row: 'freddie-cordisDefineRow__row',
  separator: 'freddie-cordisDefineRow__separator',
  name: 'freddie-cordisDefineRow__name',
  purpose: 'freddie-cordisDefineRow__purpose',
  errorSummary: 'freddie-cordisDefineRow__errorSummary',
  requestError: 'freddie-cordisDefineRow__requestError',
  readout: 'freddie-cordisDefineRow__readout',
  panelHint: 'freddie-cordisDefineRow__panelHint',
  statusLabel: 'freddie-cordisDefineRow__statusLabel',
  approvalPrompt: 'freddie-cordisDefineRow__approvalPrompt',
  notice: 'freddie-cordisDefineRow__notice',
  switch: 'freddie-cordisDefineRow__switch',
  bodyWrap: 'freddie-cordisDefineRow__bodyWrap',
  sourceCard: 'freddie-cordisDefineRow__sourceCard',
  sourceTabs: 'freddie-cordisDefineRow__sourceTabs',
  sourceTab: 'freddie-cordisDefineRow__sourceTab',
  sourceTabActive: 'freddie-cordisDefineRow__sourceTabActive',
  sourcePanel: 'freddie-cordisDefineRow__sourcePanel',
  sourceCode: 'freddie-cordisDefineRow__sourceCode',
  codeSection: 'freddie-cordisDefineRow__codeSection',
  sectionLabel: 'freddie-cordisDefineRow__sectionLabel',
  output: 'freddie-cordisDefineRow__output',
  inspectButton: 'freddie-cordisDefineRow__inspectButton',
  visuallyHidden: 'freddie-cordisDefineRow__visuallyHidden',
}

export default css
