const css = {
  layer: 'freddie-cordisPanel__layer',
  footerButtons: 'freddie-cordisPanel__footerButtons',
  badge: 'freddie-cordisPanel__badge',
  badgeLabel: 'freddie-cordisPanel__badgeLabel',
  badgeCount: 'freddie-cordisPanel__badgeCount',
  rail: 'freddie-cordisPanel__rail',
  panel: 'freddie-cordisPanel__panel',
  header: 'freddie-cordisPanel__header',
  body: 'freddie-cordisPanel__body',
  title: 'freddie-cordisPanel__title',
  note: 'freddie-cordisPanel__note',
  readError: 'freddie-cordisPanel__readError',
  group: 'freddie-cordisPanel__group',
  rows: 'freddie-cordisPanel__rows',
  row: 'freddie-cordisPanel__row',
  rowHead: 'freddie-cordisPanel__rowHead',
  rowId: 'freddie-cordisPanel__rowId',
  rowName: 'freddie-cordisPanel__rowName',
  rowStatus: 'freddie-cordisPanel__rowStatus',
  rowDetail: 'freddie-cordisPanel__rowDetail',
  versionPicker: 'freddie-cordisPanel__versionPicker',
  rowPurpose: 'freddie-cordisPanel__rowPurpose',
  rowError: 'freddie-cordisPanel__rowError',
  rowActions: 'freddie-cordisPanel__rowActions',
  transition: 'freddie-cordisPanel__transition',
  transitionActions: 'freddie-cordisPanel__transitionActions',
  activeVersion: 'freddie-cordisPanel__activeVersion',
  actionButton: 'freddie-cordisPanel__actionButton',
  doubleCheck: 'freddie-cordisPanel__doubleCheck',
}
export default css
