const css = {
  userRow: 'freddie-messageItem__userRow',
  userStack: 'freddie-messageItem__userStack',
  bubble: 'freddie-messageItem__bubble',
  referenceSummary: 'freddie-messageItem__referenceSummary',
  contextRow: 'freddie-messageItem__contextRow',
  compactionRow: 'freddie-messageItem__compactionRow',
  compactionButton: 'freddie-messageItem__compactionButton',
  compactionLeading: 'freddie-messageItem__compactionLeading',
  compactionContextIcon: 'freddie-messageItem__compactionContextIcon',
  compactionDisclosureIcon: 'freddie-messageItem__compactionDisclosureIcon',
  compactionTitle: 'freddie-messageItem__compactionTitle',
  compactionSep: 'freddie-messageItem__compactionSep',
  compactionSummary: 'freddie-messageItem__compactionSummary',
  compactionBody: 'freddie-messageItem__compactionBody',
  retryRow: 'freddie-messageItem__retryRow',
  retrySummary: 'freddie-messageItem__retrySummary',
  retryText: 'freddie-messageItem__retryText',
  retryDetails: 'freddie-messageItem__retryDetails',
  retryDetailLabel: 'freddie-messageItem__retryDetailLabel',
  turnErrorRow: 'freddie-messageItem__turnErrorRow',
  turnErrorDot: 'freddie-messageItem__turnErrorDot',
  turnErrorCopy: 'freddie-messageItem__turnErrorCopy',
  turnErrorTitle: 'freddie-messageItem__turnErrorTitle',
  turnErrorMessage: 'freddie-messageItem__turnErrorMessage',
  turnErrorCode: 'freddie-messageItem__turnErrorCode',
  maxTokensTitle: 'freddie-messageItem__maxTokensTitle',
  refChip: 'freddie-messageItem__refChip',
  refIcon: 'freddie-messageItem__refIcon',
}
export default css
