const css = {
  root: 'freddie-conversationRoot__root',
  header: 'freddie-conversationRoot__header',
  headerHidden: 'freddie-conversationRoot__headerHidden',
  titleRow: 'freddie-conversationRoot__titleRow',
  titleCluster: 'freddie-conversationRoot__titleCluster',
  crumbs: 'freddie-conversationRoot__crumbs',
  crumbSeg: 'freddie-conversationRoot__crumbSeg',
  crumbSep: 'freddie-conversationRoot__crumbSep',
  crumb: 'freddie-conversationRoot__crumb',
  crumbSubagent: 'freddie-conversationRoot__crumbSubagent',
  crumbCurrent: 'freddie-conversationRoot__crumbCurrent',
  headerActions: 'freddie-conversationRoot__headerActions',
  headerUtilities: 'freddie-conversationRoot__headerUtilities',
  tabs: 'freddie-conversationRoot__tabs',
  tab: 'freddie-conversationRoot__tab',
  tabActive: 'freddie-conversationRoot__tabActive',
  viewArea: 'freddie-conversationRoot__viewArea',
  composerStack: 'freddie-conversationRoot__composerStack',
  composerSeat: 'freddie-conversationRoot__composerSeat',
  scrollBody: 'freddie-conversationRoot__scrollBody',
  composerHero: 'freddie-conversationRoot__composerHero',
  heroWorkspaceRow: 'freddie-conversationRoot__heroWorkspaceRow',
}
export default css
