const css = {
  root: 'freddie-inputBar__root',
  hero: 'freddie-inputBar__hero',
  notice: 'freddie-inputBar__notice',
  card: 'freddie-inputBar__card',
  cardWorkspaceTrigger: 'freddie-inputBar__cardWorkspaceTrigger',
  accessory: 'freddie-inputBar__accessory',
  overlayAnchor: 'freddie-inputBar__overlayAnchor',
  scroll: 'freddie-inputBar__scroll',
  grow: 'freddie-inputBar__grow',
  backdrop: 'freddie-inputBar__backdrop',
  backdropDisabled: 'freddie-inputBar__backdropDisabled',
  hlToken: 'freddie-inputBar__hlToken',
  hlSegment: 'freddie-inputBar__hlSegment',
  hint: 'freddie-inputBar__hint',
  pending: 'freddie-inputBar__pending',
  input: 'freddie-inputBar__input',
  mirror: 'freddie-inputBar__mirror',
  row: 'freddie-inputBar__row',
  tools: 'freddie-inputBar__tools',
  modes: 'freddie-inputBar__modes',
  trailing: 'freddie-inputBar__trailing',
  add: 'freddie-inputBar__add',
  select: 'freddie-inputBar__select',
  primary: 'freddie-inputBar__primary',
  retry: 'freddie-inputBar__retry',
  textRef: 'freddie-inputBar__textRef',
  textRefTrigger: 'freddie-inputBar__textRefTrigger',
  textRefTriggerGlyph: 'freddie-inputBar__textRefTriggerGlyph',
  textRefIcon: 'freddie-inputBar__textRefIcon',
  chip: 'freddie-inputBar__chip',
  chipTrigger: 'freddie-inputBar__chipTrigger',
  chipTriggerGlyph: 'freddie-inputBar__chipTriggerGlyph',
  chipIcon: 'freddie-inputBar__chipIcon',
  chipInvalid: 'freddie-inputBar__chipInvalid',
}

export default css
