const css = {
  root: 'freddie-toolRow__root',
  row: 'freddie-toolRow__row',
  leading: 'freddie-toolRow__leading',
  chevron: 'freddie-toolRow__chevron',
  title: 'freddie-toolRow__title',
  sep: 'freddie-toolRow__sep',
  summary: 'freddie-toolRow__summary',
  summarySuffix: 'freddie-toolRow__summarySuffix',
  fileLink: 'freddie-toolRow__fileLink',
  errorSummary: 'freddie-toolRow__errorSummary',
  bodyWrap: 'freddie-toolRow__bodyWrap',
  inspectButton: 'freddie-toolRow__inspectButton',
  bodyScroll: 'freddie-toolRow__bodyScroll',
  ioCard: 'freddie-toolRow__ioCard',
  ioSection: 'freddie-toolRow__ioSection',
  ioLabel: 'freddie-toolRow__ioLabel',
  ioDivider: 'freddie-toolRow__ioDivider',
  ioText: 'freddie-toolRow__ioText',
  codeBody: 'freddie-toolRow__codeBody',
  terminalBody: 'freddie-toolRow__terminalBody',
  diffBody: 'freddie-toolRow__diffBody',
  readBody: 'freddie-toolRow__readBody',
  searchBody: 'freddie-toolRow__searchBody',
  webBody: 'freddie-toolRow__webBody',
  searchRecovery: 'freddie-toolRow__searchRecovery',
  visuallyHidden: 'freddie-toolRow__visuallyHidden',
}
export default css
