const css = {
  projectRow: 'freddie-rows__projectRow',
  sessionRow: 'freddie-rows__sessionRow',
  selected: 'freddie-rows__selected',
  searchResultRow: 'freddie-rows__searchResultRow',
  searchResultHeading: 'freddie-rows__searchResultHeading',
  searchResultTitle: 'freddie-rows__searchResultTitle',
  searchResultMeta: 'freddie-rows__searchResultMeta',
  searchResultWorkspace: 'freddie-rows__searchResultWorkspace',
  searchResultSnippet: 'freddie-rows__searchResultSnippet',
  rowActions: 'freddie-rows__rowActions',
  title: 'freddie-rows__title',
  flatSessionRowWithoutStatus: 'freddie-rows__flatSessionRowWithoutStatus',
  slot: 'freddie-rows__slot',
  visuallyHidden: 'freddie-rows__visuallyHidden',
  folderActive: 'freddie-rows__folderActive',
  chevron: 'freddie-rows__chevron',
  folder: 'freddie-rows__folder',
  arrow: 'freddie-rows__arrow',
  arrowOpen: 'freddie-rows__arrowOpen',
  projectText: 'freddie-rows__projectText',
  renameInput: 'freddie-rows__renameInput',
  meta: 'freddie-rows__meta',
  time: 'freddie-rows__time',
  dot: 'freddie-rows__dot',
  menuOpen: 'freddie-rows__menuOpen',
  dropBefore: 'freddie-rows__dropBefore',
  dropAfter: 'freddie-rows__dropAfter',
  hoverContent: 'freddie-rows__hoverContent',
  hoverTitle: 'freddie-rows__hoverTitle',
  hoverPath: 'freddie-rows__hoverPath',
  hoverTime: 'freddie-rows__hoverTime',
  hoverStatus: 'freddie-rows__hoverStatus',
  iconButton: 'freddie-rows__iconButton',
}
export default css
