const css = {
  root: 'freddie-subagentHeaderLineage__root',
  switcherRoot: 'freddie-subagentHeaderLineage__switcherRoot',
  trigger: 'freddie-subagentHeaderLineage__trigger',
  switcherTrigger: 'freddie-subagentHeaderLineage__switcherTrigger',
  ancestorSwitcherTrigger: 'freddie-subagentHeaderLineage__ancestorSwitcherTrigger',
  switcherTitle: 'freddie-subagentHeaderLineage__switcherTitle',
  separator: 'freddie-subagentHeaderLineage__separator',
  activitySlot: 'freddie-subagentHeaderLineage__activitySlot',
  triggerOpen: 'freddie-subagentHeaderLineage__triggerOpen',
  menu: 'freddie-subagentHeaderLineage__menu',
  node: 'freddie-subagentHeaderLineage__node',
  row: 'freddie-subagentHeaderLineage__row',
  clickarea: 'freddie-subagentHeaderLineage__clickarea',
  disabled: 'freddie-subagentHeaderLineage__disabled',
  loadingRow: 'freddie-subagentHeaderLineage__loadingRow',
  disclosure: 'freddie-subagentHeaderLineage__disclosure',
  disclosureSpace: 'freddie-subagentHeaderLineage__disclosureSpace',
  disclosureOpen: 'freddie-subagentHeaderLineage__disclosureOpen',
  content: 'freddie-subagentHeaderLineage__content',
  label: 'freddie-subagentHeaderLineage__label',
  summary: 'freddie-subagentHeaderLineage__summary',
  currentLabel: 'freddie-subagentHeaderLineage__currentLabel',
  metrics: 'freddie-subagentHeaderLineage__metrics',
  metricToken: 'freddie-subagentHeaderLineage__metricToken',
  metricDuration: 'freddie-subagentHeaderLineage__metricDuration',
  children: 'freddie-subagentHeaderLineage__children',
  notice: 'freddie-subagentHeaderLineage__notice',
  error: 'freddie-subagentHeaderLineage__error',
  refresh: 'freddie-subagentHeaderLineage__refresh',
}
export default css
