const css = {
  root: 'freddie-observability__root',
  bluf: 'freddie-observability__bluf',
  eyebrow: 'freddie-observability__eyebrow',
  tabs: 'freddie-observability__tabs',
  tab: 'freddie-observability__tab',
  tabActive: 'freddie-observability__tabActive',
  panel: 'freddie-observability__panel',
  panelHeader: 'freddie-observability__panelHeader',
  panelCopy: 'freddie-observability__panelCopy',
  empty: 'freddie-observability__empty',
  metrics: 'freddie-observability__metrics',
  metric: 'freddie-observability__metric',
  label: 'freddie-observability__label',
  value: 'freddie-observability__value',
  detail: 'freddie-observability__detail',
  action: 'freddie-observability__action',
  terminal: 'freddie-observability__terminal',
  output: 'freddie-observability__output',
  input: 'freddie-observability__input',
  terminalHeader: 'freddie-observability__terminalHeader',
  terminalStatus: 'freddie-observability__terminalStatus',
  snapshot: 'freddie-observability__snapshot',
  controls: 'freddie-observability__controls',
  activity: 'freddie-observability__activity',
  logList: 'freddie-observability__logList',
  memberGroup: 'freddie-observability__memberGroup',
  treeActivity: 'freddie-observability__treeActivity',
  terminalOwner: 'freddie-observability__terminalOwner',
}
export default css
