const css = {
  root: 'freddie-jsonTree__root',
  container: 'freddie-jsonTree__container',
  expandedTopLevel: 'freddie-jsonTree__expandedTopLevel',
  expandedTopLevelContainer: 'freddie-jsonTree__expandedTopLevelContainer',
  row: 'freddie-jsonTree__row',
  topLevelBracket: 'freddie-jsonTree__topLevelBracket',
  children: 'freddie-jsonTree__children',
  label: 'freddie-jsonTree__label',
  clickableLabel: 'freddie-jsonTree__clickableLabel',
  stringValue: 'freddie-jsonTree__stringValue',
  numberValue: 'freddie-jsonTree__numberValue',
  keywordValue: 'freddie-jsonTree__keywordValue',
  otherValue: 'freddie-jsonTree__otherValue',
  punctuation: 'freddie-jsonTree__punctuation',
  preview: 'freddie-jsonTree__preview',
  previewProperty: 'freddie-jsonTree__previewProperty',
  previewEllipsis: 'freddie-jsonTree__previewEllipsis',
  copyAnchor: 'freddie-jsonTree__copyAnchor',
  copyButton: 'freddie-jsonTree__copyButton',
  expander: 'freddie-jsonTree__expander',
  collapseIcon: 'freddie-jsonTree__collapseIcon',
  collapsedContent: 'freddie-jsonTree__collapsedContent',
}

export default css
